---
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6
        with:
          go-version: "stable"

      - uses: actions/golangci-lint@0a35821d5c230e903fcfe077583637dea1b27b47  # v9
        with:
          version: v2.1  # renovate datasource=github-releases depName=golangci/golangci-lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
