---
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: "stable"

      - uses: actions/golangci-lint@0a35821d5c230e903fcfe077583637dea1b27b47  # v9
        with:
          version: v2.1  # renovate datasource=github-releases depName=golangci/golangci-lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
