---
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: actions/goreleaser@e435ccd777264be153ace6237001ef4d979d3a7a  # v6
        with:
          distribution: goreleaser
          version: v2.11  # renovate datasource=github-releases depName=goreleaser/goreleaser
          args: release --clean
        env:
          GORELEASER_FORCE_TOKEN: gitea
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
