---
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: actions/goreleaser@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7
        with:
          distribution: goreleaser
          version: v2.11 # renovate datasource=github-releases depName=goreleaser/goreleaser
          args: release --clean
        env:
          GORELEASER_FORCE_TOKEN: gitea
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
