---
name: Release Check

on:
  push:
    paths:
      - .forgejo/workflows/release.yml
      - .forgejo/workflows/release-check.yml
      - .goreleaser.yaml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: GoReleaser Check
        uses: actions/goreleaser@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: v2.13 # renovate: datasource=github-releases depName=goreleaser/goreleaser
          args: release --snapshot --clean
        env:
          GORELEASER_FORCE_TOKEN: gitea
          GITEA_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
